### ISSUE TITLE
The application crashes on import/export

### ISSUE THREAD

**Issue by Almtesh** [n76/wifi_backend#36]
I tried to export the database, but the app crashed.
I see that there's no authorization to write to sdcard, is that normal?
I use the 1.1.4 version from F-droid.

**Comment by n76** [comment]
Seems like on Marshmallow, that is a permission that needs to be set at run time. . .

I guess I should update the app to check for write permission before trying to write the file.

**Comment by Almtesh** [comment]
Actually, I'm on Lollipop. You should perhaps add the access to storage in the manifest…

**Comment by n76** [comment]
Duh. I guess I should have vetted the pull request that originally added the import/export capability.

Fixed in commit 69635eb1b0e132bf72fc52f3d85fb9182d85da32 for version 1.1.5

**Comment by Almtesh** [comment]
Hi, sorry, but the issue is still there. I have the 1.1.5 version from F-droid.

**Comment by Almtesh** [comment]
@n76 Err, I can't reopen the issue, is that normal?

**Comment by n76** [comment]
Is the "storage" permission granted to it in your system app settings?

**Comment by Almtesh** [comment]
Yes, it is. Currently, the app has GPS, storage write and wi-fi access.
I don't know how it could help you, I got this in the logcat:

E/AndroidRuntime(17854): Process: org.fitchfamily.android.wifi_backend, PID: 17854
E/AndroidRuntime(17854): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/comma-separated-values }
E/AndroidRuntime(17854):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
E/AndroidRuntime(17854):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/AndroidRuntime(17854):        at android.app.Activity.startActivityForResult(Activity.java:3745)
E/AndroidRuntime(17854):        at android.app.Activity.startActivityForResult(Activity.java:3706)
E/AndroidRuntime(17854):        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:855)
E/AndroidRuntime(17854):        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
E/AndroidRuntime(17854):        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:927)
E/AndroidRuntime(17854):        at org.fitchfamily.android.wifi_backend.ui.MainSettingsFragment$4.onPreferenceClick(MainSettingsFragment.java:100)
E/AndroidRuntime(17854):        at android.preference.Preference.performClick(Preference.java:985)
E/AndroidRuntime(17854):        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
E/AndroidRuntime(17854):        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(17854):        at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime(17854):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
E/AndroidRuntime(17854):        at android.widget.AbsListView$3.run(AbsListView.java:3864)
E/AndroidRuntime(17854):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(17854):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17854):        at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(17854):        at android.app.ActivityThread.main(ActivityThread.java:5371)
E/AndroidRuntime(17854):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17854):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17854):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
E/AndroidRuntime(17854):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

**Comment by Almtesh** [comment]
Sorry, I did import, this is the logcat for export:

E/AndroidRuntime(18634): FATAL EXCEPTION: main
E/AndroidRuntime(18634): Process: org.fitchfamily.android.wifi_backend, PID: 18634
E/AndroidRuntime(18634): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/comma-separated-values (has extras) }
E/AndroidRuntime(18634):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
E/AndroidRuntime(18634):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/AndroidRuntime(18634):        at android.app.Activity.startActivityForResult(Activity.java:3745)
E/AndroidRuntime(18634):        at android.app.Activity.startActivityForResult(Activity.java:3706)
E/AndroidRuntime(18634):        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:855)
E/AndroidRuntime(18634):        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
E/AndroidRuntime(18634):        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:927)
E/AndroidRuntime(18634):        at org.fitchfamily.android.wifi_backend.ui.MainSettingsFragment$3.onPreferenceClick(MainSettingsFragment.java:83)
E/AndroidRuntime(18634):        at android.preference.Preference.performClick(Preference.java:985)
E/AndroidRuntime(18634):        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
E/AndroidRuntime(18634):        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(18634):        at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime(18634):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
E/AndroidRuntime(18634):        at android.widget.AbsListView.onTouchUp(AbsListView.java:3876)
E/AndroidRuntime(18634):        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3641)
E/AndroidRuntime(18634):        at android.view.View.dispatchTouchEvent(View.java:8547)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
E/AndroidRuntime(18634):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
E/AndroidRuntime(18634):        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
E/AndroidRuntime(18634):        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
E/AndroidRuntime(18634):        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
E/AndroidRuntime(18634):        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime(18634):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
E/AndroidRuntime(18634):        at android.view.View.dispatchPointerEvent(View.java:8742)
E/AndroidRuntime(18634):        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
E/AndroidRuntime(18634):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
E/AndroidRuntime(18634):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
E/AndroidRuntime(18634):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
E/AndroidRuntime(18634):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:

**Comment by Almtesh** [comment]
Do you have any news about this issue? This still does not work.

**Comment by n76** [comment]
What version of Android are you running?

Reason I ask is this:

`E/AndroidRuntime(18634): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/comma-separated-values (has extras) }`

It seems that you don't have support in your OS for mapping comma separated value (CSV) file types.

**Comment by Almtesh** [comment]
That's Android 5.1.1 and I don't want to open it, I just want to save it.
Must I install a app to open CSV?

**Comment by n76** [comment]
Shouldn't have to install an app that can read CSV in order to write the data. . . I am currently on a AOSP 6.1 ROM but I had this working on a 5.1 ROM earlier. I'll review the API that I am using to see what Android versions it requires and any other requirements.

**Comment by Almtesh** [comment]
I ask this because I have a Android far from AOSP, I tried to get  it more free with root access, I perhaps uninstalled an app that does this.

**Comment by n76** [comment]
IIRC it depends on a table mapping file extensions into MIME types that is compiled into the system. The question in my mind (haven't had time to check yet) is if that particular API was released after your version of the OS.
